import Gameboard from "./Gameboard";
import Plane from "./Plane";
import blockType from "../util/blockType";
import drawBlocks from "../util/drawBlocks";

xit("tests gameboard creation", () => {
  const gameBoard = Gameboard();

  expect(gameBoard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.NOT_DEFINED },
    { x: 5, y: 8, type: blockType.NOT_DEFINED },
    { x: 6, y: 8, type: blockType.NOT_DEFINED },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.NOT_DEFINED },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.NOT_DEFINED },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.NOT_DEFINED },
    { x: 5, y: 6, type: blockType.NOT_DEFINED },
    { x: 6, y: 6, type: blockType.NOT_DEFINED },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.NOT_DEFINED },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("gameboard adds a plane", () => {
  const gameboard = Gameboard();
  const plane = Plane({ x: 5, y: 5 });

  expect(gameboard.addPlane(plane)).toStrictEqual(true);

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.BODY },
    { x: 5, y: 8, type: blockType.BODY },
    { x: 6, y: 8, type: blockType.BODY },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.BODY },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.NOT_DEFINED },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.BODY },
    { x: 5, y: 6, type: blockType.BODY },
    { x: 6, y: 6, type: blockType.BODY },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.HEAD },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("does not add planes outside of gameboard", () => {
  const gameBoard = Gameboard();

  expect(gameBoard.addPlane(Plane({ x: 0, y: 0 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 1, y: 7 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 9, y: 0 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 9, y: 7 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 5, y: 7 }))).toStrictEqual(false);

  expect(gameBoard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.NOT_DEFINED },
    { x: 5, y: 8, type: blockType.NOT_DEFINED },
    { x: 6, y: 8, type: blockType.NOT_DEFINED },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.NOT_DEFINED },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.NOT_DEFINED },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.NOT_DEFINED },
    { x: 5, y: 6, type: blockType.NOT_DEFINED },
    { x: 6, y: 6, type: blockType.NOT_DEFINED },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.NOT_DEFINED },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("gameboard does not add collision plane", () => {
  const gameBoard = Gameboard();

  expect(gameBoard.addPlane(Plane({ x: 5, y: 5 }))).toStrictEqual(true);
  expect(gameBoard.addPlane(Plane({ x: 5, y: 4 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 5, y: 8 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 5, y: 2 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 4, y: 5 }))).toStrictEqual(false);
  expect(gameBoard.addPlane(Plane({ x: 7, y: 5 }))).toStrictEqual(false);

  expect(gameBoard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.BODY },
    { x: 5, y: 8, type: blockType.BODY },
    { x: 6, y: 8, type: blockType.BODY },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.BODY },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.NOT_DEFINED },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.BODY },
    { x: 5, y: 6, type: blockType.BODY },
    { x: 6, y: 6, type: blockType.BODY },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.HEAD },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("adds plane object to planes", () => {
  const gameboard = Gameboard();
  const plane = Plane({ x: 5, y: 5 });

  const planes = [];
  planes.push(plane);
  gameboard.addPlane(plane);

  expect(gameboard.getPlanes()).toStrictEqual(planes);
});

xit("adds multiple planes wxithout collision", () => {
  const gameboard = Gameboard();
  const plane1 = Plane({ x: 5, y: 5 });
  const plane2 = Plane({ x: 3, y: 4 });
  const plane3 = Plane({ x: 8, y: 4 });

  expect(gameboard.addPlane(plane1)).toStrictEqual(true);
  expect(gameboard.addPlane(plane2)).toStrictEqual(true);
  expect(gameboard.addPlane(plane3)).toStrictEqual(true);

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },
    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.BODY },
    { x: 5, y: 8, type: blockType.BODY },
    { x: 6, y: 8, type: blockType.BODY },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },
    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.BODY },
    { x: 3, y: 7, type: blockType.BODY },
    { x: 4, y: 7, type: blockType.BODY },
    { x: 5, y: 7, type: blockType.BODY },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.BODY },
    { x: 8, y: 7, type: blockType.BODY },
    { x: 9, y: 7, type: blockType.BODY },
    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.BODY },
    { x: 4, y: 6, type: blockType.BODY },
    { x: 5, y: 6, type: blockType.BODY },
    { x: 6, y: 6, type: blockType.BODY },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.BODY },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },
    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.BODY },
    { x: 3, y: 5, type: blockType.BODY },
    { x: 4, y: 5, type: blockType.BODY },
    { x: 5, y: 5, type: blockType.HEAD },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.BODY },
    { x: 8, y: 5, type: blockType.BODY },
    { x: 9, y: 5, type: blockType.BODY },
    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.HEAD },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.HEAD },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },
    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },
    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },
    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },
    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("adds multiple planes object to planes", () => {
  const gameboard = Gameboard();
  const plane1 = Plane({ x: 1, y: 1 });
  const plane2 = Plane({ x: 5, y: 2 });
  const plane3 = Plane({ x: 7, y: 6 });
  const planes = [];
  planes.push(plane1);
  planes.push(plane2);
  planes.push(plane3);
  expect(gameboard.addPlane(plane1)).toStrictEqual(true);
  expect(gameboard.addPlane(plane2)).toStrictEqual(true);
  expect(gameboard.addPlane(plane3)).toStrictEqual(true);

  expect(gameboard.getPlanes()).toStrictEqual(planes);
});

xit("adds plane and rotates", () => {
  const gameboard = Gameboard();
  const plane1 = Plane({ x: 1, y: 2 });
  const plane2 = Plane({ x: 7, y: 5 });

  gameboard.addPlane(plane1);
  gameboard.addPlane(plane2);
  gameboard.rotate(plane2);

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.NOT_DEFINED },
    { x: 5, y: 8, type: blockType.NOT_DEFINED },
    { x: 6, y: 8, type: blockType.NOT_DEFINED },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.NOT_DEFINED },
    { x: 6, y: 7, type: blockType.BODY },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.BODY },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.NOT_DEFINED },
    { x: 5, y: 6, type: blockType.NOT_DEFINED },
    { x: 6, y: 6, type: blockType.BODY },
    { x: 7, y: 6, type: blockType.BODY },
    { x: 8, y: 6, type: blockType.BODY },
    { x: 9, y: 6, type: blockType.HEAD },

    { x: 0, y: 5, type: blockType.BODY },
    { x: 1, y: 5, type: blockType.BODY },
    { x: 2, y: 5, type: blockType.BODY },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.NOT_DEFINED },
    { x: 6, y: 5, type: blockType.BODY },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.BODY },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.BODY },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.BODY },
    { x: 1, y: 3, type: blockType.BODY },
    { x: 2, y: 3, type: blockType.BODY },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.HEAD },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("hxits", () => {
  const gameboard = Gameboard();

  gameboard.hxit({ x: 2, y: 2 });

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.NOT_DEFINED },
    { x: 5, y: 8, type: blockType.NOT_DEFINED },
    { x: 6, y: 8, type: blockType.NOT_DEFINED },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.NOT_DEFINED },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.NOT_DEFINED },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.NOT_DEFINED },
    { x: 5, y: 6, type: blockType.NOT_DEFINED },
    { x: 6, y: 6, type: blockType.NOT_DEFINED },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.NOT_DEFINED },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.HxitMISS },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("hxits near plane", () => {
  const gameboard = Gameboard();
  const plane = Plane({ x: 5, y: 5 });

  gameboard.addPlane(plane);

  gameboard.hxit({ x: 4, y: 7 });

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.BODY },
    { x: 5, y: 8, type: blockType.BODY },
    { x: 6, y: 8, type: blockType.BODY },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.HxitMISS },
    { x: 5, y: 7, type: blockType.BODY },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.NOT_DEFINED },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.BODY },
    { x: 5, y: 6, type: blockType.BODY },
    { x: 6, y: 6, type: blockType.BODY },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.HEAD },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("hxits plane head", () => {
  const gameboard = Gameboard();
  const plane = Plane({ x: 5, y: 5 });

  gameboard.addPlane(plane);

  gameboard.hxit({ x: 5, y: 5 });

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.Hxit },
    { x: 5, y: 8, type: blockType.Hxit },
    { x: 6, y: 8, type: blockType.Hxit },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.Hxit },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.NOT_DEFINED },
    { x: 8, y: 7, type: blockType.NOT_DEFINED },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.Hxit },
    { x: 5, y: 6, type: blockType.Hxit },
    { x: 6, y: 6, type: blockType.Hxit },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.Hxit },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("adds multiple planes hxits one in the head", () => {
  const gameboard = Gameboard();
  const plane1 = Plane({ x: 5, y: 5 });
  const plane2 = Plane({ x: 3, y: 4 });
  const plane3 = Plane({ x: 8, y: 4 });

  expect(gameboard.addPlane(plane1)).toStrictEqual(true);
  expect(gameboard.addPlane(plane2)).toStrictEqual(true);
  expect(gameboard.addPlane(plane3)).toStrictEqual(true);

  gameboard.hxit({ x: 5, y: 5 });

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.NOT_DEFINED },
    { x: 7, y: 9, type: blockType.NOT_DEFINED },
    { x: 8, y: 9, type: blockType.NOT_DEFINED },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.Hxit },
    { x: 5, y: 8, type: blockType.Hxit },
    { x: 6, y: 8, type: blockType.Hxit },
    { x: 7, y: 8, type: blockType.NOT_DEFINED },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.BODY },
    { x: 3, y: 7, type: blockType.BODY },
    { x: 4, y: 7, type: blockType.BODY },
    { x: 5, y: 7, type: blockType.Hxit },
    { x: 6, y: 7, type: blockType.NOT_DEFINED },
    { x: 7, y: 7, type: blockType.BODY },
    { x: 8, y: 7, type: blockType.BODY },
    { x: 9, y: 7, type: blockType.BODY },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.BODY },
    { x: 4, y: 6, type: blockType.Hxit },
    { x: 5, y: 6, type: blockType.Hxit },
    { x: 6, y: 6, type: blockType.Hxit },
    { x: 7, y: 6, type: blockType.NOT_DEFINED },
    { x: 8, y: 6, type: blockType.BODY },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.BODY },
    { x: 3, y: 5, type: blockType.BODY },
    { x: 4, y: 5, type: blockType.BODY },
    { x: 5, y: 5, type: blockType.Hxit },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.BODY },
    { x: 8, y: 5, type: blockType.BODY },
    { x: 9, y: 5, type: blockType.BODY },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.HEAD },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.HEAD },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("moves plane selected on head", () => {
  const gameboard = Gameboard();
  const plane = Plane({ x: 5, y: 5 });

  expect(gameboard.addPlane(plane)).toStrictEqual(true);

  gameboard.selectPlane({ x: 5, y: 5 });
  gameboard.moveSelectedPlane({ x: 5, y: 5 }, { x: 7, y: 6 });

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.BODY },
    { x: 7, y: 9, type: blockType.BODY },
    { x: 8, y: 9, type: blockType.BODY },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.NOT_DEFINED },
    { x: 5, y: 8, type: blockType.NOT_DEFINED },
    { x: 6, y: 8, type: blockType.NOT_DEFINED },
    { x: 7, y: 8, type: blockType.BODY },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.NOT_DEFINED },
    { x: 6, y: 7, type: blockType.BODY },
    { x: 7, y: 7, type: blockType.BODY },
    { x: 8, y: 7, type: blockType.BODY },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.NOT_DEFINED },
    { x: 5, y: 6, type: blockType.NOT_DEFINED },
    { x: 6, y: 6, type: blockType.NOT_DEFINED },
    { x: 7, y: 6, type: blockType.HEAD },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.NOT_DEFINED },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});

xit("moves plane selected on body", () => {
  const gameboard = Gameboard();
  const plane = Plane({ x: 5, y: 5 });

  expect(gameboard.addPlane(plane)).toStrictEqual(true);

  gameboard.selectPlane({ x: 4, y: 6 });
  gameboard.moveSelectedPlane({ x: 4, y: 6 }, { x: 6, y: 7 });

  expect(gameboard.getBlocks()).toStrictEqual([
    { x: 0, y: 9, type: blockType.NOT_DEFINED },
    { x: 1, y: 9, type: blockType.NOT_DEFINED },
    { x: 2, y: 9, type: blockType.NOT_DEFINED },
    { x: 3, y: 9, type: blockType.NOT_DEFINED },
    { x: 4, y: 9, type: blockType.NOT_DEFINED },
    { x: 5, y: 9, type: blockType.NOT_DEFINED },
    { x: 6, y: 9, type: blockType.BODY },
    { x: 7, y: 9, type: blockType.BODY },
    { x: 8, y: 9, type: blockType.BODY },
    { x: 9, y: 9, type: blockType.NOT_DEFINED },

    { x: 0, y: 8, type: blockType.NOT_DEFINED },
    { x: 1, y: 8, type: blockType.NOT_DEFINED },
    { x: 2, y: 8, type: blockType.NOT_DEFINED },
    { x: 3, y: 8, type: blockType.NOT_DEFINED },
    { x: 4, y: 8, type: blockType.NOT_DEFINED },
    { x: 5, y: 8, type: blockType.NOT_DEFINED },
    { x: 6, y: 8, type: blockType.NOT_DEFINED },
    { x: 7, y: 8, type: blockType.BODY },
    { x: 8, y: 8, type: blockType.NOT_DEFINED },
    { x: 9, y: 8, type: blockType.NOT_DEFINED },

    { x: 0, y: 7, type: blockType.NOT_DEFINED },
    { x: 1, y: 7, type: blockType.NOT_DEFINED },
    { x: 2, y: 7, type: blockType.NOT_DEFINED },
    { x: 3, y: 7, type: blockType.NOT_DEFINED },
    { x: 4, y: 7, type: blockType.NOT_DEFINED },
    { x: 5, y: 7, type: blockType.NOT_DEFINED },
    { x: 6, y: 7, type: blockType.BODY },
    { x: 7, y: 7, type: blockType.BODY },
    { x: 8, y: 7, type: blockType.BODY },
    { x: 9, y: 7, type: blockType.NOT_DEFINED },

    { x: 0, y: 6, type: blockType.NOT_DEFINED },
    { x: 1, y: 6, type: blockType.NOT_DEFINED },
    { x: 2, y: 6, type: blockType.NOT_DEFINED },
    { x: 3, y: 6, type: blockType.NOT_DEFINED },
    { x: 4, y: 6, type: blockType.NOT_DEFINED },
    { x: 5, y: 6, type: blockType.NOT_DEFINED },
    { x: 6, y: 6, type: blockType.NOT_DEFINED },
    { x: 7, y: 6, type: blockType.HEAD },
    { x: 8, y: 6, type: blockType.NOT_DEFINED },
    { x: 9, y: 6, type: blockType.NOT_DEFINED },

    { x: 0, y: 5, type: blockType.NOT_DEFINED },
    { x: 1, y: 5, type: blockType.NOT_DEFINED },
    { x: 2, y: 5, type: blockType.NOT_DEFINED },
    { x: 3, y: 5, type: blockType.NOT_DEFINED },
    { x: 4, y: 5, type: blockType.NOT_DEFINED },
    { x: 5, y: 5, type: blockType.NOT_DEFINED },
    { x: 6, y: 5, type: blockType.NOT_DEFINED },
    { x: 7, y: 5, type: blockType.NOT_DEFINED },
    { x: 8, y: 5, type: blockType.NOT_DEFINED },
    { x: 9, y: 5, type: blockType.NOT_DEFINED },

    { x: 0, y: 4, type: blockType.NOT_DEFINED },
    { x: 1, y: 4, type: blockType.NOT_DEFINED },
    { x: 2, y: 4, type: blockType.NOT_DEFINED },
    { x: 3, y: 4, type: blockType.NOT_DEFINED },
    { x: 4, y: 4, type: blockType.NOT_DEFINED },
    { x: 5, y: 4, type: blockType.NOT_DEFINED },
    { x: 6, y: 4, type: blockType.NOT_DEFINED },
    { x: 7, y: 4, type: blockType.NOT_DEFINED },
    { x: 8, y: 4, type: blockType.NOT_DEFINED },
    { x: 9, y: 4, type: blockType.NOT_DEFINED },

    { x: 0, y: 3, type: blockType.NOT_DEFINED },
    { x: 1, y: 3, type: blockType.NOT_DEFINED },
    { x: 2, y: 3, type: blockType.NOT_DEFINED },
    { x: 3, y: 3, type: blockType.NOT_DEFINED },
    { x: 4, y: 3, type: blockType.NOT_DEFINED },
    { x: 5, y: 3, type: blockType.NOT_DEFINED },
    { x: 6, y: 3, type: blockType.NOT_DEFINED },
    { x: 7, y: 3, type: blockType.NOT_DEFINED },
    { x: 8, y: 3, type: blockType.NOT_DEFINED },
    { x: 9, y: 3, type: blockType.NOT_DEFINED },

    { x: 0, y: 2, type: blockType.NOT_DEFINED },
    { x: 1, y: 2, type: blockType.NOT_DEFINED },
    { x: 2, y: 2, type: blockType.NOT_DEFINED },
    { x: 3, y: 2, type: blockType.NOT_DEFINED },
    { x: 4, y: 2, type: blockType.NOT_DEFINED },
    { x: 5, y: 2, type: blockType.NOT_DEFINED },
    { x: 6, y: 2, type: blockType.NOT_DEFINED },
    { x: 7, y: 2, type: blockType.NOT_DEFINED },
    { x: 8, y: 2, type: blockType.NOT_DEFINED },
    { x: 9, y: 2, type: blockType.NOT_DEFINED },

    { x: 0, y: 1, type: blockType.NOT_DEFINED },
    { x: 1, y: 1, type: blockType.NOT_DEFINED },
    { x: 2, y: 1, type: blockType.NOT_DEFINED },
    { x: 3, y: 1, type: blockType.NOT_DEFINED },
    { x: 4, y: 1, type: blockType.NOT_DEFINED },
    { x: 5, y: 1, type: blockType.NOT_DEFINED },
    { x: 6, y: 1, type: blockType.NOT_DEFINED },
    { x: 7, y: 1, type: blockType.NOT_DEFINED },
    { x: 8, y: 1, type: blockType.NOT_DEFINED },
    { x: 9, y: 1, type: blockType.NOT_DEFINED },

    { x: 0, y: 0, type: blockType.NOT_DEFINED },
    { x: 1, y: 0, type: blockType.NOT_DEFINED },
    { x: 2, y: 0, type: blockType.NOT_DEFINED },
    { x: 3, y: 0, type: blockType.NOT_DEFINED },
    { x: 4, y: 0, type: blockType.NOT_DEFINED },
    { x: 5, y: 0, type: blockType.NOT_DEFINED },
    { x: 6, y: 0, type: blockType.NOT_DEFINED },
    { x: 7, y: 0, type: blockType.NOT_DEFINED },
    { x: 8, y: 0, type: blockType.NOT_DEFINED },
    { x: 9, y: 0, type: blockType.NOT_DEFINED },
  ]);
});
